### ISSUE TITLE
Setup Gatsby boilerplate

### ISSUE THREAD

**Issue by abhishek71994** [GirlScriptSummerOfCode/Zero_Gravity#1]
---
name: Setup Gatsby boilerplate
about: the purpose of this issue is to setup a basic gatsbyJS application

---

## Expected Behavior
The application is expected to have a functional component working along with SCSS setup.

## Current Behavior
At present there is no basic setup in the repo

## Possible Solution
Check this link out : https://www.gatsbyjs.org/tutorial/part-one/

**Comment by adarshlilha** [comment]
want to work on this.

**Comment by abhishek71994** [comment]
Go for it @adarshlilha

**Comment by abhishek71994** [comment]
Thank you @adarshlilha
